const mongoose = require('mongoose')

const estimateSchema = new mongoose.Schema({
  projectId: {
    type:     mongoose.Schema.Types.ObjectId,
    ref:      'Project',
    required: true
  },

  estimateName: {
    type:     String,
    required: true,
    trim:     true
  },

  estimateType: {
    type:    String,
    enum:    ['RoomBased', 'PackageBased', 'Revision'],
    default: 'RoomBased'
  },

  status: {
    type:    String,
    enum:    ['Draft', 'Locked'],
    default: 'Draft'
  },

  // Pointer to the active version
  currentVersion: {
    type:    Number,
    default: 1
  },

  // Snapshot of active version totals — kept in sync on every save
  computedTotals: {
    subtotal:      { type: Number, default: 0 },
    totalCost:     { type: Number, default: 0 },
    totalSell:     { type: Number, default: 0 },
    marginAmount:  { type: Number, default: 0 },
    marginPercent: { type: Number, default: 0 }
  },

  // Engine context — stored so recalculation can reference original inputs
  budgetContext: {
    totalBudget:      { type: Number, default: null },
    budgetPerSqft:    { type: Number, default: null },
    targetMarginBand: {
      min: { type: Number, default: null },
      max: { type: Number, default: null }
    }
  },

  // Whether this estimate was generated by the AI engine or created manually
  generatedByEngine: {
    type:    Boolean,
    default: false
  },

  createdBy: {
    type:     mongoose.Schema.Types.ObjectId,
    ref:      'User',
    required: true
  }
}, { timestamps: true })

estimateSchema.index({ projectId: 1, createdAt: -1 })

module.exports = mongoose.model('Estimate', estimateSchema)
