/**
 * Shared calculation helpers.
 * Pure functions — no DB calls, no side effects.
 * Used by estimateController and projectFinanceController.
 */

const toNum = (val) => {
  const n = parseFloat(val)
  return isNaN(n) ? 0 : n
}

/**
 * Recursively calculates computed values for one item.
 * Handles children first (bottom-up aggregation).
 *
 * Calculation rules:
 *   area  = width × height  (if both present and column mode is 'auto')
 *   total = area × rate     (or qty × rate if no area column)
 *   pricing group col total = col_rate × col_qty
 */
function calculateItemComputed(item, columns) {
  const computed = {}
  const vals = item.values instanceof Map
    ? Object.fromEntries(item.values)
    : (item.values || {})

  const mode = (col) => col.calculationMode || 'auto'

  // ── Children first — parent total = sum of children ───────────────────────
  if (item.children && item.children.length > 0) {
    let childTotal = 0
    item.children = item.children.map(child => {
      const childComputed = calculateItemComputed(child, columns)
      child.computed = childComputed
      childTotal += childComputed.subtotal || childComputed.total || 0
      return child
    })
    computed.subtotal  = childTotal
    computed.finalTotal = parseFloat((childTotal * 1.18).toFixed(2))
    computed.total     = childTotal
    return computed
  }

  // ── Area column ───────────────────────────────────────────────────────────
  const areaCol = columns.find(c => c.id === 'area' || c.id === 'square')
  if (areaCol && mode(areaCol) === 'auto') {
    computed[areaCol.id] = toNum(vals.width) * toNum(vals.height)
  }

  // ── Engine-style estimate: materialRate + laborRate + quantity ─────────────
  // Handles estimates generated by the prediction engine.
  // subtotal = qty * (materialRate + laborRate)
  // finalTotal = subtotal * 1.18 (18% GST, same as engine default)
  const hasMR  = toNum(vals.materialRate) > 0
  const hasLR  = toNum(vals.laborRate) > 0
  const hasQty = toNum(vals.quantity || vals.qty) > 0

  if (hasMR || hasLR) {
    const qty      = toNum(vals.quantity || vals.qty || 1)
    const mr       = toNum(vals.materialRate || 0)
    const lr       = toNum(vals.laborRate    || 0)
    const subtotal = parseFloat((qty * (mr + lr)).toFixed(2))
    computed.subtotal   = subtotal
    computed.finalTotal = parseFloat((subtotal * 1.18).toFixed(2))
    computed.total      = subtotal   // keep 'total' for legacy column compatibility
  }

  // ── Total column (legacy / custom estimates) ───────────────────────────────
  const totalCol = columns.find(c => c.id === 'total')
  if (totalCol && mode(totalCol) === 'auto' && !computed.total) {
    const area = computed.square ?? computed.area
      ?? toNum(vals.square || vals.area || 0)
    const qty  = toNum(vals.quantity || vals.qty || 0)
    computed.total    = (area || qty) * toNum(vals.rate || vals.materialRate || 0)
    computed.subtotal = computed.total
  }

  // ── Pricing group columns ─────────────────────────────────────────────────
  columns.forEach(col => {
    if (col.link && mode(col) === 'auto') {
      const rateKey = `${col.link}_rate`
      const qtyKey  = `${col.link}_qty`
      computed[col.id] = toNum(vals[rateKey]) * toNum(vals[qtyKey])
    }
  })

  return computed
}

/**
 * Recalculates all items in all categories and returns:
 *   - updated categories (with computed values filled)
 *   - computedTotals for the whole estimate
 */
function recalculateCategories(categories) {
  let subtotal = 0

  const updatedCategories = categories.map(cat => {
    const updatedItems = (cat.items || []).map(item => {
      const computed = calculateItemComputed(item, cat.columns || [])
      return {
        ...item,
        computed: typeof computed === 'object' && !(computed instanceof Map)
          ? new Map(Object.entries(computed))
          : computed
      }
    })

    // Category subtotal — engine items use 'subtotal', legacy items use 'total'
    const catTotal = updatedItems.reduce((sum, item) => {
      const c = item.computed instanceof Map
        ? Object.fromEntries(item.computed)
        : (item.computed || {})
      const v = toNum(c.subtotal || 0) > 0 ? toNum(c.subtotal) : toNum(c.total || 0)
      return sum + v
    }, 0)

    subtotal += catTotal

    return {
      ...cat,
      items: updatedItems,
      computedTotals: {
        totalCost:     catTotal,
        totalSell:     catTotal,
        marginAmount:  0,
        marginPercent: 0
      }
    }
  })

  return {
    categories: updatedCategories,
    computedTotals: {
      subtotal,
      totalCost:     subtotal,
      totalSell:     subtotal,
      marginAmount:  0,
      marginPercent: 0
    }
  }
}

/**
 * Calculates ProjectFinance totals from an array of estimate refs.
 */
function calculateFinanceTotals(estimates, gstEnabled, gstPercentage) {
  const subtotal = estimates
    .filter(e => e.includedInBudget)
    .reduce((sum, e) => sum + toNum(e.subtotal), 0)

  const gstAmount  = gstEnabled ? (subtotal * toNum(gstPercentage)) / 100 : 0
  const grandTotal = subtotal + gstAmount

  return { subtotal, gstAmount, grandTotal }
}

module.exports = { calculateItemComputed, recalculateCategories, calculateFinanceTotals }
